/**
 * Public read-only SDF team/people index.
 *
 *   GET /api/people                     # full roster (leadership, board, advisors)
 *   GET /api/people?q=justin%20rice     # name / role / org lookup
 *   GET /api/people?section=board       # one section
 *
 * The org/people reference for the Stellar Development Foundation roster —
 * leadership, board of directors, and advisors — quoted from
 * stellar.org/foundation/team with provenance. This is deliberately DISTINCT
 * from /api/builders (GitHub-contributor profiles from Stellar Passport): a VP
 * of Ecosystem or a board member is not a "builder". Answers "who is <person>",
 * "what's their role", "who leads <area> at SDF", "who's on the board".
 *
 * Served from a committed registry (src/data/sdf-people.ts, regenerated by
 * scripts/build-sdf-people.ts) — no DB dependency, deterministic for the
 * contract-drift guard.
 */
import { type NextRequest, NextResponse } from "next/server";
import { logApiHit } from "@/lib/api-usage";
import { clampLimit } from "@/lib/http-params";
import { methodNotAllowed } from "@/lib/method-not-allowed";
import {
	normalizeSection,
	PEOPLE_OBSERVED_AT,
	PEOPLE_SOURCE,
	searchPeople,
	sectionsAvailable,
} from "@/lib/sdf-people";

export const dynamic = "force-dynamic";
export const revalidate = 3600;

const SUPPORTED_PARAMS = ["q", "section", "limit", "offset"] as const;

const MATCH_BASIS =
	"Name/role/org text match over the SDF roster (leadership, board of directors, advisors) quoted from stellar.org/foundation/team. This is an ORG/PEOPLE reference index, NOT a builder/contributor index — for GitHub builders use /api/builders, for doc/spec authorship use /api/research. Rows are roster facts, not verified availability or contact info.";

export async function GET(req: NextRequest) {
	const sp = req.nextUrl.searchParams;

	// Strict unknown-param rejection (mirrors /api/builders): a dropped param
	// silently returns the full roster while the caller believes they filtered.
	const unknownParams = [...new Set(sp.keys())].filter(
		(k) => !(SUPPORTED_PARAMS as readonly string[]).includes(k),
	);
	if (unknownParams.length) {
		return NextResponse.json(
			{
				error: `Unsupported query parameter(s): ${unknownParams.join(", ")}.`,
				supportedParams: SUPPORTED_PARAMS,
			},
			{ status: 400 },
		);
	}

	const q = sp.get("q")?.trim() || null;
	const sectionRaw = sp.get("section")?.trim() || null;
	const section = normalizeSection(sectionRaw);
	// A section filter that names no real section is a 400 (consistent with the
	// type/status validators elsewhere) — never a silent empty "as if filtered".
	if (sectionRaw && !section) {
		return NextResponse.json(
			{
				error: `Invalid section '${sectionRaw}'.`,
				validSections: sectionsAvailable(),
			},
			{ status: 400 },
		);
	}

	const limit = clampLimit(sp.get("limit"), 50, 100);
	const offset = Math.max(Number(sp.get("offset") || "0") || 0, 0);

	const { people, total } = searchPeople(q, { section, limit, offset });

	logApiHit({
		req,
		endpoint: "/api/people",
		query: q ?? "",
		filters: { section, limit },
	});

	// Honest zero-result advisory: name lookups that miss are almost always
	// people who aren't on the SDF roster at all (community builders, external
	// authors) — route them to the index that DOES cover them, and never imply
	// the roster is empty.
	const advisory =
		total > 0
			? undefined
			: {
					summary: q
						? `No SDF roster entry matches "${q}". This index covers only the Stellar Development Foundation's own leadership, board, and advisors (${sectionsAvailable().join(", ")}). For a GitHub-contributor/builder, try /api/builders; for a doc, spec, or blog author, try /api/research.`
						: "The SDF people index returned no rows for this filter.",
					tryInstead: [
						{
							endpoint: "/api/builders",
							why: "GitHub-contributor / builder profiles (Stellar Passport)",
						},
						{
							endpoint: "/api/research",
							why: "doc / spec / blog authorship across the SDF corpus",
						},
					],
				};

	return NextResponse.json(
		{
			meta: {
				source: PEOPLE_SOURCE,
				observedAt: PEOPLE_OBSERVED_AT,
				generatedAt: new Date().toISOString(),
				filters: { q, section, limit, offset },
				counts: { returned: people.length, total },
				sections: sectionsAvailable(),
				matchBasis: MATCH_BASIS,
				...(advisory ? { advisory } : {}),
			},
			people,
		},
		{
			headers: {
				"Cache-Control": "public, s-maxage=3600, stale-while-revalidate=7200",
			},
		},
	);
}

export const POST = methodNotAllowed(["GET"]);
export const PUT = methodNotAllowed(["GET"]);
export const DELETE = methodNotAllowed(["GET"]);
export const PATCH = methodNotAllowed(["GET"]);
