/**
 * Generate src/data/cap-registry.ts — the structured CAP crosswalk table:
 * one row per core CAP with its number, title, Status, and the Protocol
 * version that shipped it, parsed from each CAP's own preamble.
 *
 * This is the join table the code-truth layer needs (soroban-sdk version ⇄
 * protocol version ⇄ CAPs); the research corpus holds the PROSE (ingest-caps),
 * this holds the FACTS. CAP headers change a few times a year — regenerate and
 * PR when they do (a shallow git clone is used, so no GitHub API rate limits).
 *
 *   pnpm exec tsx scripts/data/generate-cap-registry.ts
 */
import { execSync } from "node:child_process";
import { mkdtempSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { parseCapPreamble } from "../../src/lib/cap-preamble";

// Run from the repo root (as documented above).
const OUT = join(process.cwd(), "src", "data", "cap-registry.ts");

function extractTitle(md: string, fallback: string): string {
	return md.match(/^Title:\s*(.+?)\s*$/m)?.[1] ?? fallback;
}

function main() {
	const dir = mkdtempSync(join(tmpdir(), "cap-registry-"));
	console.log(`shallow-cloning stellar/stellar-protocol → ${dir}`);
	execSync(
		`git clone --depth 1 --quiet https://github.com/stellar/stellar-protocol.git ${dir}`,
		{ stdio: "inherit" },
	);
	const coreDir = join(dir, "core");
	const files = readdirSync(coreDir)
		.filter((f) => /^cap-\d+\.md$/i.test(f))
		.sort();
	console.log(`${files.length} CAP files`);

	const rows = files.map((f) => {
		const md = readFileSync(join(coreDir, f), "utf8");
		const id = f.replace(/\.md$/i, "").toLowerCase();
		const pre = parseCapPreamble(md);
		return {
			cap: Number(id.replace("cap-", "")),
			id,
			title: extractTitle(md, id),
			status: pre.status,
			protocolVersion: pre.protocolVersion,
			url: `https://github.com/stellar/stellar-protocol/blob/master/core/${f}`,
		};
	});

	const asOf = new Date().toISOString().slice(0, 10);
	const body = `/**
 * GENERATED by scripts/data/generate-cap-registry.ts — do not hand-edit.
 * Structured CAP crosswalk parsed from each CAP's own preamble in
 * stellar/stellar-protocol (as of ${asOf}). status/protocolVersion are the
 * CAP's OWN declared fields; null = absent/TBD upstream, never guessed.
 */
export interface CapRegistryRow {
	cap: number;
	id: string;
	title: string;
	status: string | null;
	protocolVersion: number | null;
	url: string;
}

export const CAP_REGISTRY_AS_OF = "${asOf}";

export const CAP_REGISTRY: CapRegistryRow[] = ${JSON.stringify(rows, null, "\t")};
`;
	writeFileSync(OUT, body);
	const byStatus: Record<string, number> = {};
	for (const r of rows) byStatus[r.status ?? "null"] = (byStatus[r.status ?? "null"] ?? 0) + 1;
	console.log(`wrote ${OUT} (${rows.length} rows)`, byStatus);
}

main();
