/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health + endpoint enumeration
         * @description Returns service health, data-source freshness per collection, and a self-describing enumeration of all 14 endpoints. Useful as a self-discovery call before making other queries.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Stellar projects (prior art / competitor lookup)
         * @description Search the curated Stellar project directory (hundreds of projects; live count in /api/status) with tiered match-mode (strict → loose → majority). Tier surfaced as `.meta.matchMode` so agents convey relevance honestly. Essential for *'has anyone already built this?'* gap-classification questions. A bare call with no q/filter returns `meta.error: no_query` + 0 rows (it does NOT return the full directory).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Keyword query (free text) */
                    q?: components["parameters"]["q"];
                    /** @description Filter by category */
                    category?: "Infrastructure" | "Tooling" | "User-Facing App" | "Asset" | "Protocol/Contract" | "Anchor" | "Partner Integration";
                    /** @description Filter to SCF-funded projects only */
                    scfAwarded?: boolean;
                    /** @description Max results per page. The default and cap VARY by endpoint (e.g. projects/search 20/100, builders 50/200, leaderboard 50/300, research 8/25). A value below 1 or above the cap is clamped, not rejected. */
                    limit?: components["parameters"]["limit"];
                    /** @description Number of matching rows to skip before returning (pagination). Page until offset + meta.counts.returned >= meta.counts.total. */
                    offset?: components["parameters"]["offset"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project search results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectSearchResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the Stellar GitHub repo / code-reference index
         * @description Search ~1,900 indexed-and-scored Stellar ecosystem GitHub repos by tech/keyword — the code layer beneath the project directory. Answers *'show me the repos / code for X'* and prior-art **code** lookups that project search can't. Indexes GitHub topics + description + language + README, expands synonyms (zk→zero-knowledge/snark, oracle→price-feed, …), and ranks by `repoScore` (0–100 = freshness + traction + hackathon/SCF/builder authority). Lead with high-score repos as the strongest references and cite each repo's `url` / `homepageUrl`. The same graded repos are injected inline into `/api/projects/search` as `codeReferences`.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Keyword query (free text) */
                    q?: components["parameters"]["q"];
                    /** @description Filter by primary language (case-insensitive substring, e.g. 'Rust', 'TypeScript') */
                    language?: string;
                    /** @description Only return repos with repoScore ≥ this (0–100). Use 40+ for high-signal references. */
                    minScore?: number;
                    /** @description Max results per page. The default and cap VARY by endpoint (e.g. projects/search 20/100, builders 50/200, leaderboard 50/300, research 8/25). A value below 1 or above the cap is clamped, not rejected. */
                    limit?: components["parameters"]["limit"];
                    /** @description Number of matching rows to skip before returning (pagination). Page until offset + meta.counts.returned >= meta.counts.total. */
                    offset?: components["parameters"]["offset"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Repo search results graded by repoScore */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RepoSearchResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hackathons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stellar hackathons
         * @description Returns curated Stellar hackathons + live DoraHacks events. Empty status-scoped queries include fallback channels (BuildOnStellar / stellarlight / DoraHacks) so agents can route users to live announcement sources.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by event status */
                    status?: "upcoming" | "active" | "completed";
                    /** @description Filter by organizer slug */
                    organizer?: string;
                    /** @description Restrict to one feed (curated vs DoraHacks) */
                    source?: "curated" | "dorahacks";
                    /** @description Max results per page. The default and cap VARY by endpoint (e.g. projects/search 20/100, builders 50/200, leaderboard 50/300, research 8/25). A value below 1 or above the cap is clamped, not rejected. */
                    limit?: components["parameters"]["limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hackathon list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HackathonsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hackathons/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one hackathon's full detail
         * @description Returns submissions, placements, prize tracks, post-hack status funnel, and outcome data for one hackathon by slug. Dual-shape response: curated entries return full detail; DoraHacks-only entries return metadata + prize pool + an explicit `.meta.note`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Hackathon slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hackathon detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HackathonDetailResponse"];
                    };
                };
                /** @description Hackathon not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hackathons/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare 2–5 hackathons side-by-side
         * @description Returns each hackathon's stats + a `.deltas` block highlighting differences agents care about (prize spread, hacker count, prize-per-winner). Useful for *'which Stellar hackathon should I enter?'* type questions.
         */
        get: {
            parameters: {
                query: {
                    /** @description 2–5 hackathon slugs, comma-separated (?slugs=a,b) */
                    slugs: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Comparison rollup */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Stellar builders
         * @description Returns Stellar builder profiles (sourced from Stellar Passport). Useful for *'find a teammate / collaborator who has shipped in X'* queries. Small + growing dataset — flag gaps honestly.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Free-text filter over bio / role / projects (accepts `skill`/`tech` as aliases) */
                    q?: string;
                    /** @description Filter by location substring (e.g. 'Lagos', 'Brazil') */
                    location?: string;
                    /** @description Filter by skill/tech mentioned in bio */
                    skill?: string;
                    /** @description Max results per page. The default and cap VARY by endpoint (e.g. projects/search 20/100, builders 50/200, leaderboard 50/300, research 8/25). A value below 1 or above the cap is clamped, not rejected. */
                    limit?: components["parameters"]["limit"];
                    /** @description Number of matching rows to skip before returning (pagination). Page until offset + meta.counts.returned >= meta.counts.total. */
                    offset?: components["parameters"]["offset"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Builder list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List ecosystem partners
         * @description Published partners (anchors, on/off ramps, infrastructure, tooling, protocols, wallets, audit firms). Each carries partner-claimed facts AND system-verified signals (GitHub activity, on-chain footprint, SCF involvement) plus a `freshness` object — consumers should down-rank or skip partners flagged `freshness.excludeFromMatching`. Fresh partners sort first.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by partner type */
                    type?: "anchor" | "on-off-ramp" | "infrastructure" | "tooling" | "protocol" | "wallet" | "audit-firm" | "legal" | "agency" | "other";
                    /** @description Filter by sector served (defi, payments, rwa, stablecoins, …) */
                    sector?: string;
                    /** @description Filter by region served (global, latam, africa, …) */
                    region?: string;
                    /** @description Set to 1 to return only partners currently accepting new clients */
                    accepting?: "1";
                    /** @description Keyword query (free text) */
                    q?: components["parameters"]["q"];
                    /** @description Max results per page. The default and cap VARY by endpoint (e.g. projects/search 20/100, builders 50/200, leaderboard 50/300, research 8/25). A value below 1 or above the cap is clamped, not rejected. */
                    limit?: components["parameters"]["limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Partner directory */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partners/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one partner's full profile
         * @description Full published profile for one partner by slug, including verified signals + freshness. 404 for unknown or unpublished slugs.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Partner slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Partner profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Partner not found or not published */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rfps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stellar RFPs (SCF-funded sponsor briefs)
         * @description Returns open + closed Stellar RFPs (sponsor briefs that get SCF-funded for the winning team). Quarter-aware: response includes `.meta.activeQuarter` so agents know which RFPs are open *now* vs prior rounds.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Open RFPs are fundable for the current SCF quarter; closed are prior rounds */
                    status?: "open" | "closed";
                    /** @description Filter by quarter slug (e.g. 'q1-2026') */
                    quarter?: string;
                    /** @description Keyword query (free text) */
                    q?: components["parameters"]["q"];
                    /** @description Filter by RFP category (e.g. 'defi', 'payments', 'infrastructure'). An unrecognized value returns 400 with the valid category list. */
                    category?: string;
                    /** @description Max results per page. The default and cap VARY by endpoint (e.g. projects/search 20/100, builders 50/200, leaderboard 50/300, research 8/25). A value below 1 or above the cap is clamped, not rejected. */
                    limit?: components["parameters"]["limit"];
                    /** @description Number of matching rows to skip before returning (pagination). Page until offset + meta.counts.returned >= meta.counts.total. */
                    offset?: components["parameters"]["offset"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description RFP list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vector search over the Stellar research corpus
         * @description Vector search over a 4,541-chunk corpus of primary Stellar sources: SEPs, SCF Handbook, dev docs, foundational papers (Mazières SCP), lumenloop community playbooks, Soroban audit reports (Certora, OtterSec, Halborn, OpenZeppelin, Code4rena, etc.), Electric Capital Developer Reports, SDF blog. Returns top-K chunks with severity metadata for audit chunks. Each result carries a `confidence` object — `{ score (0-1), label (high/medium/low), relevance, freshness, authority, ageDays }` — blending match strength, source-aware recency, and source authority so an agent can tell a strong, fresh, canonical hit from a weak or stale one. Sort by `confidence.score` for trust-ranked results; `meta.scoreModel.version` identifies the model. The raw `score` field remains cosine similarity (0–1, higher = more relevant).
         */
        get: {
            parameters: {
                query: {
                    /** @description Natural-language search query */
                    q: string;
                    /** @description Optional source filter. Use 'audit' for security questions, 'ec-developer-report' for ecosystem stats, 'paper' for foundational protocol questions. */
                    source?: "sdf-blog" | "scf-handbook" | "sep" | "dev-docs" | "paper" | "scf-proposal" | "lumenloop" | "lumenloop-research" | "audit" | "incident" | "ec-developer-report";
                    /** @description Max results (default 8, max 25) */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Research results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List AI skills for Stellar builders
         * @description Merged catalog of SDF skills.stellar.org skills + curated Stellar Light entries + approved community submissions. Editorial source priority: Stellarlight → SDF → external ecosystem → competing aggregators → community. Featured skills sort first.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by source */
                    source?: "sdf" | "stellarlight" | "lumenloop" | "external" | "community";
                    /** @description Filter by skill kind */
                    kind?: "skill-md" | "mcp-server" | "sdk" | "cli" | "agent-kit" | "tool";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Skills catalog */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one skill's full content
         * @description Returns full SKILL.md content for SDF + Stellar Light skills (where applicable) plus metadata for all sources. Use when a user mentions a specific skill by name — cheaper than filtering the full list endpoint.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Skill slug (e.g. 'soroban', 'stellar-scout', 'rozo-intent-pay') */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Skill detail with content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Skill not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Topic clusters with crowdedness scores
         * @description Returns clusters of projects by category or types, each with a log-scaled crowdedness score (1–10), SCF-funded count, and sample projects. Useful for *'what's most crowded on Stellar?'* / *'show me underbuilt categories'* queries.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Cluster by category (coarse 7-cat) or types (finer) */
                    dimension?: "category" | "types";
                    /** @description Only include clusters with at least N projects */
                    minSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cluster list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cross-event Stellar ecosystem analytics rollup
         * @description Aggregate stats across all hackathons + projects + SCF funding. Returns: total events, prize pool totals, top categories by project count + SCF-funded count, distribution of SCF awards, post-hackathon status funnel (Built / In Progress / Abandoned).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Which slice to return */
                    dimension?: "all" | "hackathons" | "categories" | "funding";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Analytics rollup */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stellar ecosystem developer activity
         * @description Returns 28-day active dev counts, commits, full-time vs part-time vs one-time dev splits, geographic distribution. Sourced from Electric Capital. Useful for *'how does Stellar compare on dev activity?'* macro questions.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Order the project leaderboard. An unrecognized value returns 400 with the valid list. */
                    sort?: "activity" | "stars" | "issues";
                    /** @description Activity time-window for the leaderboard. An unrecognized value returns 400. */
                    range?: "7d" | "30d" | "90d" | "1y" | "all";
                    /** @description Filter the leaderboard to one project category (e.g. 'Tooling', 'Infrastructure'). An unrecognized value returns 400 with the valid list. */
                    category?: string;
                    /** @description Response format. */
                    format?: "json" | "csv";
                    /** @description Max results per page. The default and cap VARY by endpoint (e.g. projects/search 20/100, builders 50/200, leaderboard 50/300, research 8/25). A value below 1 or above the cap is clamped, not rejected. */
                    limit?: components["parameters"]["limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Leaderboard + ecosystem stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the feedback request schema (discovery)
         * @description Returns the expected POST body shape + valid `kind` values, so an agent can self-discover how to submit feedback without guessing. No side effects.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Feedback request schema */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        /**
         * Submit feedback on Scout's output
         * @description Send a feedback report when the skill returns wrong / missing / misleading information. Lands in the curator queue. Rate-limited to 6/min/IP (IP hashed with PAYLOAD_SECRET, never stored raw).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FeedbackRequest"];
                };
            };
            responses: {
                /** @description Feedback received (a curator-queue row was created) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            id: string;
                            message?: string;
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standard meta block included on every list response */
        Meta: {
            /** Format: uri */
            source?: string;
            /** Format: date-time */
            generatedAt?: string;
            filters?: {
                [key: string]: unknown;
            };
            counts?: {
                /** @description Rows in this page (post limit/offset slice) */
                returned?: number;
                /** @description Rows matching the filter before slicing (paginated endpoints). Page until offset + returned >= total. */
                total?: number;
            };
        };
        ErrorResponse: {
            error: string;
            details?: {
                [key: string]: unknown;
            };
        };
        StatusResponse: {
            ok: boolean;
            /** @constant */
            service: "Stellar Scout";
            version: string;
            /** Format: date-time */
            generatedAt: string;
            sources?: {
                name?: string;
                count?: number;
                /** Format: date-time */
                lastUpdatedAt?: string | null;
                notes?: string;
            }[];
            usage?: {
                total?: number;
                last24h?: number;
                last7d?: number;
                byEndpoint?: {
                    endpoint?: string;
                    count?: number;
                }[];
            };
            endpoints: string[];
            /** Format: uri */
            docs?: string;
            /** Format: uri */
            skill?: string;
        };
        Project: {
            id: string;
            name: string;
            slug: string;
            /** @enum {string} */
            category: "Infrastructure" | "Tooling" | "User-Facing App" | "Asset" | "Protocol/Contract" | "Anchor" | "Partner Integration";
            shortDescription?: string;
            /** @enum {string} */
            status: "Draft" | "Development" | "Pre-Release" | "Live";
            logoUrl?: string | null;
            scfAwarded?: boolean;
            scfTotalAwardedUSD?: number | null;
            hackathon?: string | null;
            hackathonPlacement?: string | null;
            hackathonPrize?: number | null;
            hackathonPrizeTrack?: string | null;
            /** @description Relevance score for the current query (higher = better match) */
            score?: number;
            /** Format: uri */
            url?: string;
            /** @description Editorial ranking boost (0-100); higher = more canonical for its category. */
            prominence?: number;
            verificationLevel?: string | null;
            /** @description Capability tags (Wallet, DEX, Lending, Oracle, SDK, RPC, Faucet, NFT, RWA, Anchor, Stablecoin, Indexer, Explorer, Security, Gaming). */
            types?: string[];
            /** @description The project OWN canonical homes - cite these as the primary source, not StellarLight or any directory. Only present, non-empty fields are included. */
            links?: {
                website?: string;
                github?: string;
                docs?: string;
                twitter?: string;
                discord?: string;
            };
        };
        ProjectSearchResponse: {
            meta: components["schemas"]["Meta"] & {
                /**
                 * @description Tier of match relaxation that produced these results
                 * @enum {string}
                 */
                matchMode?: "strict" | "loose-1" | "loose-2" | "loose-3" | "majority" | "all";
                matchModeLabel?: string;
            };
            projects: components["schemas"]["Project"][];
            /** @description Top graded repos matching the same query, surfaced inline (max 5, first page only; same shape as /api/repos/search). Cite as existing code references for prior-art questions. */
            codeReferences?: components["schemas"]["Repo"][];
        };
        HackathonsResponse: {
            meta?: components["schemas"]["Meta"] & {
                /** @description Present when the query returns 0 events — a summary plus live announcement channels to point the user at. NOTE: an OBJECT, not an array. */
                fallbackChannels?: {
                    summary?: string;
                    channels?: {
                        name?: string;
                        /** Format: uri */
                        url?: string;
                        why?: string;
                    }[];
                };
            };
            hackathons?: Record<string, never>[];
        };
        HackathonDetailResponse: {
            meta?: components["schemas"]["Meta"];
            hackathon?: Record<string, never>;
        };
        /** @description An indexed Stellar ecosystem GitHub repository graded by repoScore. Cite the repo's url / homepageUrl as the primary source. */
        Repo: {
            /** @description owner/name */
            fullName: string;
            owner?: string | null;
            name?: string | null;
            /** Format: uri */
            url?: string | null;
            description?: string | null;
            topics?: string[];
            primaryLanguage?: string | null;
            stars?: number;
            openIssues?: number;
            /** Format: date-time */
            lastCommitAt?: string | null;
            homepageUrl?: string | null;
            isFork?: boolean;
            isArchived?: boolean;
            /** @description The curated project this repo is linked to, if any. */
            project?: {
                slug?: string;
                name?: string | null;
            } | null;
            hackathonWinner?: boolean;
            scfAwarded?: boolean;
            builderReputation?: number;
            judgeScore?: number | null;
            judgedHackathon?: string | null;
            /** @description Quality grade (0–100) = freshness + traction + hackathon/SCF/builder authority. Lead with high-score repos. */
            repoScore: number;
            repoScoreLabel?: string | null;
            /** @description Keyword-relevance score for the current query (higher = better match). */
            score?: number;
        };
        RepoSearchResponse: {
            meta: components["schemas"]["Meta"];
            repos: components["schemas"]["Repo"][];
        };
        /** @description Optional reporting context is NESTED under `context` (matches the live endpoint + the GET /api/feedback self-schema). */
        FeedbackRequest: {
            /** @enum {string} */
            kind: "bug" | "missing-data" | "wrong-answer" | "suggestion" | "other";
            message: string;
            /** @description Optional context about what triggered the feedback. */
            context?: {
                query?: string;
                endpoint?: string;
                skillVersion?: string;
                agentName?: string;
            };
        };
    };
    responses: never;
    parameters: {
        /** @description Keyword query (free text) */
        q: string;
        /** @description Max results per page. The default and cap VARY by endpoint (e.g. projects/search 20/100, builders 50/200, leaderboard 50/300, research 8/25). A value below 1 or above the cap is clamped, not rejected. */
        limit: number;
        /** @description Number of matching rows to skip before returning (pagination). Page until offset + meta.counts.returned >= meta.counts.total. */
        offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
