/**
 * Build the committed SDF team/people index (src/data/sdf-people.ts) from the
 * canonical roster on stellar.org/foundation/team.
 *
 * Why a committed registry (not a Payload collection): the roster is a small
 * (~25 rows), slow-changing, single-source reference set with no user edits —
 * exactly the shape of the other curated registries (canonical-pages,
 * curation-maps). It also stays servable while the prod M0 cluster is write-
 * blocked. /api/people reads this module directly.
 *
 * Extraction reuses the sls-055 card parser (src/lib/team-cards.ts): names
 * render in <main> but the ROLES + section grouping (Leadership / Board of
 * directors / Advisors) live only in the page's __NEXT_DATA__ card blocks.
 *
 * Honesty rail: if extraction yields fewer than MIN_PEOPLE, or no Leadership
 * section, the page structure changed — REFUSE to overwrite the registry
 * (exit 1) rather than shrink it silently.
 *
 * Usage:
 *   pnpm exec tsx scripts/build-sdf-people.ts             # dry run (fetch + preview, no write)
 *   pnpm exec tsx scripts/build-sdf-people.ts --execute   # write src/data/sdf-people.ts
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { extractPersonCards } from "../src/lib/team-cards";

const TEAM_URL = "https://stellar.org/foundation/team";
const OUT_PATH = join(process.cwd(), "src/data/sdf-people.ts");
/** Below this the page is a shell/redirect or the card structure changed. */
const MIN_PEOPLE = 12;

const execute = process.argv.slice(2).includes("--execute");

/** External affiliation for a board/advisor role, or SDF for leadership.
 * Prefer the last " at X" (affiliation), then the last " of X". */
function deriveOrg(role: string, section: string | null): string {
	if (section === "Leadership") return "Stellar Development Foundation";
	const clean = (s: string) => s.replace(/^the\s+/i, "").trim();
	const at = role.match(/.*\bat\s+(.+)$/i);
	if (at) return clean(at[1]);
	const of = role.match(/.*\bof\s+(.+)$/i);
	if (of) return clean(of[1]);
	return "";
}

async function run() {
	console.log(execute ? "EXECUTE MODE" : "DRY RUN MODE");
	const res = await fetch(TEAM_URL, {
		headers: { "User-Agent": "stellarlight-scout-ingest" },
	});
	if (!res.ok) {
		console.error(`✗ fetch ${TEAM_URL}: HTTP ${res.status}`);
		process.exit(1);
	}
	const html = await res.text();
	const cards = extractPersonCards(html);

	const people = cards.map((c) => ({
		name: c.name,
		role: c.role,
		section: c.section ?? "Team",
		org: deriveOrg(c.role, c.section),
	}));

	// Honesty rail: a structural change (roles moved out of __NEXT_DATA__, page
	// rebuilt) must fail loudly, never silently shrink the shipped index.
	const sections = new Set(people.map((p) => p.section));
	if (people.length < MIN_PEOPLE || !sections.has("Leadership")) {
		console.error(
			`✗ extracted ${people.length} people (sections: ${[...sections].join(", ") || "none"}) — below floor ${MIN_PEOPLE} or missing Leadership. Roster structure likely changed; REFUSING to overwrite the registry. Inspect the live page's __NEXT_DATA__ cards.`,
		);
		process.exit(1);
	}

	console.log(`\n${people.length} people across ${sections.size} section(s):`);
	for (const p of people) {
		console.log(
			`  [${p.section}] ${p.name} — ${p.role}${p.org ? `  ·  org=${p.org}` : ""}`,
		);
	}

	if (!execute) {
		console.log(
			"\nDry run — no write. Re-run with --execute to write the registry.",
		);
		return;
	}

	const observedAt = new Date().toISOString().slice(0, 10);
	const body = `// GENERATED by scripts/build-sdf-people.ts from ${TEAM_URL}.
// Committed reference data — regenerate with:
//   pnpm exec tsx scripts/build-sdf-people.ts --execute
// Do not hand-edit; the roster is authoritative from the SDF team page.

/** One SDF team-page roster entry: a person, their current role, the roster
 * section they appear under, and their affiliation (SDF for leadership; the
 * external org for board/advisors). Reference data, NOT verified availability. */
export interface SdfPerson {
	name: string;
	role: string;
	/** "Leadership" | "Board of directors" | "Advisors". */
	section: string;
	/** Affiliation — "Stellar Development Foundation" for leadership, the
	 * external org for board/advisors, "" when the role names none. */
	org: string;
}

export const SDF_PEOPLE_SOURCE = ${JSON.stringify(TEAM_URL)};
/** Date the roster was last observed from the source page (YYYY-MM-DD). */
export const SDF_PEOPLE_OBSERVED_AT = ${JSON.stringify(observedAt)};

export const SDF_PEOPLE: SdfPerson[] = ${JSON.stringify(people, null, 2)};
`;
	writeFileSync(OUT_PATH, body, "utf8");
	console.log(
		`\n✓ wrote ${OUT_PATH} — ${people.length} people, observedAt ${observedAt}`,
	);
}

run().catch((e) => {
	console.error("FATAL:", e);
	process.exit(1);
});
