/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    blog: Blog;
    'rss-feeds': RssFeed;
    signals: Signal;
    entities: Entity;
    'transparency-logs': TransparencyLog;
    carousel: Carousel;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    projects: {
      relatedEntities: 'entities';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    'rss-feeds': RssFeedsSelect<false> | RssFeedsSelect<true>;
    signals: SignalsSelect<false> | SignalsSelect<true>;
    entities: EntitiesSelect<false> | EntitiesSelect<true>;
    'transparency-logs': TransparencyLogsSelect<false> | TransparencyLogsSelect<true>;
    carousel: CarouselSelect<false> | CarouselSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    banner: Banner;
  };
  globalsSelect: {
    banner: BannerSelect<false> | BannerSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      'sync-rss-feed': SyncRSSFeedTask;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  name: string;
  slug: string;
  /**
   * Project logo image. If not provided, a default logo will be used.
   */
  logo?: (string | null) | Media;
  shortDescription?: string | null;
  category:
    | 'Infrastructure'
    | 'Tooling'
    | 'Partner Integration'
    | 'User-Facing App'
    | 'Asset'
    | 'Protocol/Contract'
    | 'Anchor';
  types?:
    | (
        | 'Wallet'
        | 'DEX'
        | 'Lending'
        | 'Bridge'
        | 'Payment Rail'
        | 'Anchor'
        | 'SDK'
        | 'Indexer'
        | 'Explorer'
        | 'Analytics'
        | 'AI'
        | 'Gaming'
        | 'Education'
        | 'Security'
        | 'NFT'
        | 'RWA'
      )[]
    | null;
  /**
   * Draft projects require admin approval before appearing on the frontend
   */
  status: 'Draft' | 'Development' | 'Pre-Release' | 'Live';
  links?: {
    website?: string | null;
    github?: string | null;
    docs?: string | null;
    /**
     * X (formerly Twitter) profile URL (e.g., https://x.com/username)
     */
    twitter?: string | null;
    discord?: string | null;
  };
  /**
   * Link GitHub data to this project
   */
  github?: {
    /**
     * GitHub org login (optional), e.g. "stellar"
     */
    orgLogin?: string | null;
    /**
     * Specific repositories for this project (owner/name)
     */
    repos?:
      | {
          owner: string;
          name: string;
          id?: string | null;
        }[]
      | null;
  };
  onchain?: {
    assetCode?: string | null;
    issuer?: string | null;
    contracts?:
      | {
          address?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  verificationLevel: 'Unverified' | 'Verified (SDF)' | 'Verified (Community)';
  provenance: {
    source: 'LumenloopSeed' | 'UserSubmitted' | 'AdminEdit';
    sourceId?: string | null;
    firstSeenAt?: string | null;
  };
  lastVerifiedAt?: string | null;
  /**
   * Featured projects appear first in the directory when sorted by Featured.
   */
  featured?: boolean | null;
  /**
   * Mark this project as a community pick. Note: Projects must have an X (Twitter) profile link in the Links section to appear in the Community Picks section on the homepage.
   */
  communityPick?: boolean | null;
  /**
   * Entities/organizations linked to this project. Edit from either side.
   */
  relatedEntities?: {
    docs?: (string | Entity)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entities".
 */
export interface Entity {
  id: string;
  name: string;
  slug: string;
  /**
   * Entity logo image. If not provided, a default icon will be used.
   */
  logo?: (string | null) | Media;
  /**
   * Description of the entity/organization.
   */
  description?: string | null;
  domains?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  links?: {
    website?: string | null;
    github?: string | null;
    /**
     * X (formerly Twitter) profile URL (e.g., https://x.com/username)
     */
    twitter?: string | null;
  };
  projects?: (string | Project)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  /**
   * The main title of the blog post
   */
  title: string;
  /**
   * URL-friendly version of the title
   */
  slug: string;
  /**
   * Author name
   */
  author: string;
  /**
   * Short summary for preview cards (150-200 characters)
   */
  excerpt: string;
  /**
   * Hero image for the blog post
   */
  featuredImage?: (string | null) | Media;
  /**
   * Image URL from RSS feed (for external posts)
   */
  rssImageUrl?: string | null;
  /**
   * Show in highlights section
   */
  featured?: boolean | null;
  /**
   * Choose how you want to create this post
   */
  contentType: 'richText' | 'markdown';
  /**
   * Rich text content (used when Content Type is Rich Text Editor)
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Markdown content (used when Content Type is Markdown)
   */
  markdownContent?: string | null;
  /**
   * If this post was imported from an RSS feed, link to the feed source
   */
  rssFeed?: (string | null) | RssFeed;
  /**
   * Unique identifier from RSS feed item (for duplicate detection)
   */
  rssItemId?: string | null;
  /**
   * If true, this post links to an external RSS article instead of displaying content here
   */
  isRSSExternal?: boolean | null;
  /**
   * Original URL of the RSS article (for external posts)
   */
  externalUrl?: string | null;
  /**
   * Description from RSS feed (for external posts)
   */
  rssDescription?: string | null;
  category?: ('Announcement' | 'Tutorial' | 'News' | 'Technical' | 'Community' | 'Partnership' | 'Update') | null;
  /**
   * Add tags to help categorize this post
   */
  tags?: string[] | null;
  /**
   * Publication date
   */
  publishedAt?: string | null;
  status: 'draft' | 'published';
  /**
   * SEO and social media metadata
   */
  meta?: {
    /**
     * Meta description for SEO
     */
    description?: string | null;
    /**
     * SEO keywords
     */
    keywords?: string[] | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage RSS feeds that automatically import blog posts. Visit the RSS Management page to sync feeds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rss-feeds".
 */
export interface RssFeed {
  id: string;
  /**
   * A friendly name for this RSS feed (e.g., 'Stellar Blog')
   */
  name: string;
  /**
   * The full URL of the RSS feed
   */
  feedUrl: string;
  /**
   * Enable or disable automatic syncing for this feed
   */
  enabled?: boolean | null;
  /**
   * How often to sync this feed
   */
  syncFrequency: '15min' | '30min' | 'hourly' | '6hours' | 'daily' | 'manual';
  /**
   * Default author name for posts from this feed (if not specified in RSS)
   */
  author?: string | null;
  /**
   * Default category for posts from this feed
   */
  category?: ('Announcement' | 'Tutorial' | 'News' | 'Technical' | 'Community' | 'Partnership' | 'Update') | null;
  /**
   * Default tags to add to all posts from this feed
   */
  tags?: string[] | null;
  /**
   * Automatically publish imported posts (otherwise they'll be drafts)
   */
  autoPublish?: boolean | null;
  /**
   * Last time this feed was successfully synced
   */
  lastSyncedAt?: string | null;
  /**
   * Status of the last sync attempt
   */
  lastSyncStatus?: ('Success' | 'Failed' | 'Never') | null;
  /**
   * Error message from the last failed sync (if any)
   */
  lastSyncError?: string | null;
  /**
   * Total number of posts imported from this feed
   */
  totalPostsImported?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signals".
 */
export interface Signal {
  id: string;
  project: string | Project;
  fetchedAt?: string | null;
  github?: {
    lastActivityAt?: string | null;
    openIssuesTotal?: number | null;
    repos?:
      | {
          owner?: string | null;
          name?: string | null;
          url?: string | null;
          lastCommitAt?: string | null;
          openIssues?: number | null;
          error?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transparency-logs".
 */
export interface TransparencyLog {
  id: string;
  action: 'Create' | 'Update' | 'SyncImport' | 'Intake';
  actorType: 'System' | 'User' | 'Admin';
  targetCollection: string;
  targetId: string;
  diff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  timestamp: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carousel".
 */
export interface Carousel {
  id: string;
  /**
   * Name/identifier for this carousel item
   */
  name: string;
  /**
   * Logo/image to display in the carousel
   */
  image: string | Media;
  /**
   * Optional URL to link to when clicked
   */
  url?: string | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  /**
   * Show this item in the carousel
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sync-rss-feed';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sync-rss-feed') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'blog';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'rss-feeds';
        value: string | RssFeed;
      } | null)
    | ({
        relationTo: 'signals';
        value: string | Signal;
      } | null)
    | ({
        relationTo: 'entities';
        value: string | Entity;
      } | null)
    | ({
        relationTo: 'transparency-logs';
        value: string | TransparencyLog;
      } | null)
    | ({
        relationTo: 'carousel';
        value: string | Carousel;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  shortDescription?: T;
  category?: T;
  types?: T;
  status?: T;
  links?:
    | T
    | {
        website?: T;
        github?: T;
        docs?: T;
        twitter?: T;
        discord?: T;
      };
  github?:
    | T
    | {
        orgLogin?: T;
        repos?:
          | T
          | {
              owner?: T;
              name?: T;
              id?: T;
            };
      };
  onchain?:
    | T
    | {
        assetCode?: T;
        issuer?: T;
        contracts?:
          | T
          | {
              address?: T;
              id?: T;
            };
      };
  verificationLevel?: T;
  provenance?:
    | T
    | {
        source?: T;
        sourceId?: T;
        firstSeenAt?: T;
      };
  lastVerifiedAt?: T;
  featured?: T;
  communityPick?: T;
  relatedEntities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  excerpt?: T;
  featuredImage?: T;
  rssImageUrl?: T;
  featured?: T;
  contentType?: T;
  content?: T;
  markdownContent?: T;
  rssFeed?: T;
  rssItemId?: T;
  isRSSExternal?: T;
  externalUrl?: T;
  rssDescription?: T;
  category?: T;
  tags?: T;
  publishedAt?: T;
  status?: T;
  meta?:
    | T
    | {
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rss-feeds_select".
 */
export interface RssFeedsSelect<T extends boolean = true> {
  name?: T;
  feedUrl?: T;
  enabled?: T;
  syncFrequency?: T;
  author?: T;
  category?: T;
  tags?: T;
  autoPublish?: T;
  lastSyncedAt?: T;
  lastSyncStatus?: T;
  lastSyncError?: T;
  totalPostsImported?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signals_select".
 */
export interface SignalsSelect<T extends boolean = true> {
  project?: T;
  fetchedAt?: T;
  github?:
    | T
    | {
        lastActivityAt?: T;
        openIssuesTotal?: T;
        repos?:
          | T
          | {
              owner?: T;
              name?: T;
              url?: T;
              lastCommitAt?: T;
              openIssues?: T;
              error?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entities_select".
 */
export interface EntitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  description?: T;
  domains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  links?:
    | T
    | {
        website?: T;
        github?: T;
        twitter?: T;
      };
  projects?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transparency-logs_select".
 */
export interface TransparencyLogsSelect<T extends boolean = true> {
  action?: T;
  actorType?: T;
  targetCollection?: T;
  targetId?: T;
  diff?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carousel_select".
 */
export interface CarouselSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  url?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configure the site-wide top banner
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner".
 */
export interface Banner {
  id: string;
  /**
   * Turn the banner ON or OFF
   */
  enabled?: boolean | null;
  /**
   * Banner message to display (max 150 characters)
   */
  message?: string | null;
  /**
   * Optional URL - when set, the banner becomes clickable
   */
  linkUrl?: string | null;
  /**
   * Choose a background color for the banner
   */
  backgroundColor?: ('primary' | 'blue' | 'green' | 'amber' | 'red' | 'gray') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner_select".
 */
export interface BannerSelect<T extends boolean = true> {
  enabled?: T;
  message?: T;
  linkUrl?: T;
  backgroundColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SyncRSSFeedTask".
 */
export interface SyncRSSFeedTask {
  input: {
    feedId?: string | null;
    syncAll?: boolean | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}