// GENERATED by scripts/build-sdf-people.ts from https://stellar.org/foundation/team.
// Committed reference data — regenerate with:
//   pnpm exec tsx scripts/build-sdf-people.ts --execute
// Do not hand-edit; the roster is authoritative from the SDF team page.

/** One SDF team-page roster entry: a person, their current role, the roster
 * section they appear under, and their affiliation (SDF for leadership; the
 * external org for board/advisors). Reference data, NOT verified availability. */
export interface SdfPerson {
	name: string;
	role: string;
	/** "Leadership" | "Board of directors" | "Advisors". */
	section: string;
	/** Affiliation — "Stellar Development Foundation" for leadership, the
	 * external org for board/advisors, "" when the role names none. */
	org: string;
}

export const SDF_PEOPLE_SOURCE = "https://stellar.org/foundation/team";
/** Date the roster was last observed from the source page (YYYY-MM-DD). */
export const SDF_PEOPLE_OBSERVED_AT = "2026-07-19";

export const SDF_PEOPLE: SdfPerson[] = [
	{
		name: "Candace Kelly",
		role: "Chief Legal and Policy Officer",
		section: "Leadership",
		org: "Stellar Development Foundation",
	},
	{
		name: "David Mazières",
		role: "Founder and Chief Scientist",
		section: "Leadership",
		org: "Stellar Development Foundation",
	},
	{
		name: "Denelle Dixon",
		role: "CEO and Executive Director",
		section: "Leadership",
		org: "Stellar Development Foundation",
	},
	{
		name: "Jason Karsh",
		role: "Chief Marketing Officer",
		section: "Leadership",
		org: "Stellar Development Foundation",
	},
	{
		name: "Jed McCaleb",
		role: "Founder and Chief Architect",
		section: "Leadership",
		org: "Stellar Development Foundation",
	},
	{
		name: "Jose Fernandez da Ponte",
		role: "President & Chief Growth Officer",
		section: "Leadership",
		org: "Stellar Development Foundation",
	},
	{
		name: "Justin Rice",
		role: "VP of Ecosystem",
		section: "Leadership",
		org: "Stellar Development Foundation",
	},
	{
		name: "Lisa Macnew",
		role: "VP of People",
		section: "Leadership",
		org: "Stellar Development Foundation",
	},
	{
		name: "Liz Ray",
		role: "Chief Financial Officer",
		section: "Leadership",
		org: "Stellar Development Foundation",
	},
	{
		name: "Nicolas Barry",
		role: "Chief Technology Officer",
		section: "Leadership",
		org: "Stellar Development Foundation",
	},
	{
		name: "Raja Chakravorti",
		role: "Chief Business Officer",
		section: "Leadership",
		org: "Stellar Development Foundation",
	},
	{
		name: "Tomer Weller",
		role: "Chief Product Officer",
		section: "Leadership",
		org: "Stellar Development Foundation",
	},
	{
		name: "Jed McCaleb",
		role: "Co-Founder and Chief Architect at Stellar Development Foundation",
		section: "Board of directors",
		org: "Stellar Development Foundation",
	},
	{
		name: "Lin-Hua Wu",
		role: "SVP and Chief Communications Officer at General Motors",
		section: "Board of directors",
		org: "General Motors",
	},
	{
		name: "Ronaldo Lemos",
		role: "Professor of International and Public Affairs and Partner at PNM Advogados",
		section: "Board of directors",
		org: "PNM Advogados",
	},
	{
		name: "Ginger Baker",
		role: "VP, Product at Meta",
		section: "Board of directors",
		org: "Meta",
	},
	{
		name: "Asiff Hirji",
		role: "President of MoonPay",
		section: "Board of directors",
		org: "MoonPay",
	},
	{
		name: "Patrick Collison",
		role: "CEO of Stripe",
		section: "Advisors",
		org: "Stripe",
	},
	{
		name: "Sam Altman",
		role: "CEO of OpenAI",
		section: "Advisors",
		org: "OpenAI",
	},
	{
		name: "Naval Ravikant",
		role: "Founder of AngelList",
		section: "Advisors",
		org: "AngelList",
	},
	{
		name: "Matt Mullenweg",
		role: "Founder of WordPress.com",
		section: "Advisors",
		org: "WordPress.com",
	},
	{
		name: "Greg Stein",
		role: "Director at the Apache Software Foundation",
		section: "Advisors",
		org: "Apache Software Foundation",
	},
	{
		name: "Keith Rabois",
		role: "General Partner at Founders Fund",
		section: "Advisors",
		org: "Founders Fund",
	},
	{
		name: "Bhagwan Chowdhry",
		role: "Professor at UCLA Anderson",
		section: "Advisors",
		org: "UCLA Anderson",
	},
	{
		name: "Dan Kaminsky",
		role: "PAST ADVISOR",
		section: "Advisors",
		org: "",
	},
];
